export const EXERCISE_CATALOG = [
  { name: "Piegamenti", muscleGroup: "Petto", slug: "push-up" },
  { name: "Squat", muscleGroup: "Gambe", slug: "squat" },
  { name: "Plank", muscleGroup: "Core", slug: "plank" },
  { name: "Crunch", muscleGroup: "Core", slug: "crunch" },
  { name: "Affondi", muscleGroup: "Gambe", slug: "lunge" },
  { name: "Shoulder press", muscleGroup: "Spalle", slug: "shoulder-press" },
  { name: "Curl bicipiti", muscleGroup: "Bicipiti", slug: "biceps-curl" },
  { name: "Mountain climber", muscleGroup: "Core", slug: "mountain-climber" },
  { name: "Burpee", muscleGroup: "Full body", slug: "burpee" },
  { name: "Jumping jack", muscleGroup: "Cardio", slug: "jumping-jack" },
  { name: "Panca manubri", muscleGroup: "Petto", slug: "dumbbell-bench-press" },
  { name: "Rematore manubrio", muscleGroup: "Dorso", slug: "dumbbell-row" },
  { name: "Glute bridge", muscleGroup: "Glutei", slug: "glute-bridge" },
  { name: "Dip tricipiti", muscleGroup: "Tricipiti", slug: "triceps-dip" },
  { name: "Side plank", muscleGroup: "Core", slug: "side-plank" },
  { name: "Stacco da terra", muscleGroup: "Gambe", slug: "deadlift" },
  { name: "Lat machine / trazioni assistite", muscleGroup: "Dorso", slug: "lat-machine-assisted-pull-up" },
  { name: "Leg press", muscleGroup: "Gambe", slug: "leg-press" },
  { name: "Leg curl", muscleGroup: "Gambe", slug: "leg-curl" },
  { name: "Calf raise", muscleGroup: "Polpacci", slug: "calf-raise" },
  { name: "Russian twist", muscleGroup: "Core", slug: "russian-twist" },
  { name: "Sit-up", muscleGroup: "Core", slug: "sit-up" },
  { name: "Hip thrust", muscleGroup: "Glutei", slug: "hip-thrust" },
  { name: "Alzate laterali", muscleGroup: "Spalle", slug: "lateral-raise" },
  { name: "Military press / push press", muscleGroup: "Spalle", slug: "military-press-push-press" },
  { name: "Pull-up / trazione sbarra", muscleGroup: "Dorso", slug: "pull-up" },
  { name: "Cable row / pulley basso", muscleGroup: "Dorso", slug: "cable-row" },
  { name: "Croci manubri", muscleGroup: "Petto", slug: "dumbbell-chest-fly" },
  { name: "Triceps pushdown", muscleGroup: "Tricipiti", slug: "triceps-pushdown" },
  { name: "Hammer curl", muscleGroup: "Bicipiti", slug: "hammer-curl" },
  { name: "Leg extension", muscleGroup: "Gambe", slug: "leg-extension" },
  { name: "Bulgarian split squat", muscleGroup: "Gambe", slug: "bulgarian-split-squat" },
  { name: "Step-up box", muscleGroup: "Gambe", slug: "step-up-box" },
  { name: "Kettlebell swing", muscleGroup: "Full body", slug: "kettlebell-swing" },
  { name: "Bicycle crunch", muscleGroup: "Core", slug: "bicycle-crunch" },
  { name: "Curl con bilanciere", muscleGroup: "Bicipiti", slug: "barbell-curl" },
  { name: "Trazioni", muscleGroup: "Dorso", slug: "trazioni" },
  { name: "French press", muscleGroup: "Tricipiti", slug: "french-press" },
  { name: "Lat machine", muscleGroup: "Dorso", slug: "lat-machine" },
  { name: "Rematore con bilanciere", muscleGroup: "Dorso", slug: "barbell-row" },
  { name: "Pressa", muscleGroup: "Gambe", slug: "pressa" },
  { name: "Croci ai cavi", muscleGroup: "Petto", slug: "cable-chest-fly" },
  { name: "Spinte con manubri", muscleGroup: "Petto", slug: "dumbbell-press" },
  { name: "Lento avanti", muscleGroup: "Spalle", slug: "lento-avanti" },
  { name: "Panca piana", muscleGroup: "Petto", slug: "flat-bench-press" },
  { name: "High knees", muscleGroup: "Cardio", slug: "high-knees" },
  { name: "Battle ropes", muscleGroup: "Cardio", slug: "battle-ropes" },
  { name: "Calf raise seduto", muscleGroup: "Polpacci", slug: "seated-calf-raise" },
  { name: "Slanci glutei al cavo", muscleGroup: "Glutei", slug: "cable-glute-kickback" },
  { name: "Abductor machine", muscleGroup: "Glutei", slug: "hip-abductor-machine" },
  { name: "Farmer walk", muscleGroup: "Full body", slug: "farmer-walk" },
  { name: "Preacher curl", muscleGroup: "Bicipiti", slug: "preacher-curl" },
  { name: "Estensioni tricipiti sopra testa", muscleGroup: "Tricipiti", slug: "overhead-triceps-extension" },
  { name: "Face pull", muscleGroup: "Spalle", slug: "face-pull" },
  { name: "Reverse fly", muscleGroup: "Spalle", slug: "reverse-fly" },
  { name: "Calf raise in piedi", muscleGroup: "Polpacci", slug: "standing-calf-raise" },
  { name: "Donkey calf raise", muscleGroup: "Polpacci", slug: "donkey-calf-raise" },
  { name: "Curl concentrato", muscleGroup: "Bicipiti", slug: "concentration-curl" },
  { name: "Curl manubri inclinato", muscleGroup: "Bicipiti", slug: "incline-dumbbell-curl" },
  { name: "Dip su panca", muscleGroup: "Tricipiti", slug: "bench-dips" },
  { name: "Clean and press", muscleGroup: "Full body", slug: "clean-and-press" },
  { name: "Medicine ball slam", muscleGroup: "Full body", slug: "medicine-ball-slam" },
  { name: "Box jump", muscleGroup: "Cardio", slug: "box-jump" },
  { name: "Salto con la corda", muscleGroup: "Cardio", slug: "jump-rope" },
  { name: "Cable pull-through", muscleGroup: "Glutei", slug: "cable-pull-through" },
  { name: "Calf raise monopodalico", muscleGroup: "Polpacci", slug: "single-leg-calf-raise" },
  { name: "Tibialis raise", muscleGroup: "Polpacci", slug: "tibialis-raise" },
  { name: "Sled push", muscleGroup: "Full body", slug: "sled-push" },
  { name: "Rowing machine", muscleGroup: "Cardio", slug: "rowing-machine" },
  { name: "Cable woodchopper", muscleGroup: "Core", slug: "cable-woodchopper" },
  { name: "Alzata laterale al cavo", muscleGroup: "Spalle", slug: "cable-lateral-raise" },
  { name: "Diamond push-up", muscleGroup: "Petto", slug: "diamond-push-up" },
  { name: "Estensione tricipiti con corda", muscleGroup: "Tricipiti", slug: "rope-overhead-triceps-extension" },
  { name: "Back extension", muscleGroup: "Dorso", slug: "back-extension" },
  { name: "Hanging leg raise", muscleGroup: "Core", slug: "hanging-leg-raise" },
];

export const EXERCISE_SLUG_BY_NAME = new Map(EXERCISE_CATALOG.map((exercise) => [exercise.name, exercise.slug]));
