export const EXERCISE_CATALOG = [
  { name: "Piegamenti", muscleGroup: "Petto", slug: "push-up", loadType: "body" },
  { name: "Squat", muscleGroup: "Gambe", slug: "squat", loadType: "weight" },
  { name: "Plank", muscleGroup: "Core", slug: "plank", loadType: "time" },
  { name: "Crunch", muscleGroup: "Core", slug: "crunch", loadType: "body" },
  { name: "Affondi", muscleGroup: "Gambe", slug: "lunge", loadType: "body" },
  { name: "Shoulder press", muscleGroup: "Spalle", slug: "shoulder-press", loadType: "weight" },
  { name: "Curl bicipiti", muscleGroup: "Bicipiti", slug: "biceps-curl", loadType: "weight" },
  { name: "Mountain climber", muscleGroup: "Core", slug: "mountain-climber", loadType: "time" },
  { name: "Burpee", muscleGroup: "Full body", slug: "burpee", loadType: "body" },
  { name: "Jumping jack", muscleGroup: "Cardio", slug: "jumping-jack", loadType: "time" },
  { name: "Panca manubri", muscleGroup: "Petto", slug: "dumbbell-bench-press", loadType: "weight" },
  { name: "Rematore manubrio", muscleGroup: "Dorso", slug: "dumbbell-row", loadType: "weight" },
  { name: "Glute bridge", muscleGroup: "Glutei", slug: "glute-bridge", loadType: "body" },
  { name: "Dip tricipiti", muscleGroup: "Tricipiti", slug: "triceps-dip", loadType: "body" },
  { name: "Side plank", muscleGroup: "Core", slug: "side-plank", loadType: "time" },
  { name: "Stacco da terra", muscleGroup: "Gambe", slug: "deadlift", loadType: "weight" },
  { name: "Lat machine / trazioni assistite", muscleGroup: "Dorso", slug: "lat-machine-assisted-pull-up", loadType: "weight" },
  { name: "Leg press", muscleGroup: "Gambe", slug: "leg-press", loadType: "weight" },
  { name: "Leg curl", muscleGroup: "Gambe", slug: "leg-curl", loadType: "weight" },
  { name: "Calf raise", muscleGroup: "Polpacci", slug: "calf-raise", loadType: "body" },
  { name: "Russian twist", muscleGroup: "Core", slug: "russian-twist", loadType: "body" },
  { name: "Sit-up", muscleGroup: "Core", slug: "sit-up", loadType: "body" },
  { name: "Hip thrust", muscleGroup: "Glutei", slug: "hip-thrust", loadType: "weight" },
  { name: "Alzate laterali", muscleGroup: "Spalle", slug: "lateral-raise", loadType: "weight" },
  { name: "Military press / push press", muscleGroup: "Spalle", slug: "military-press-push-press", loadType: "weight" },
  { name: "Pull-up / trazione sbarra", muscleGroup: "Dorso", slug: "pull-up", loadType: "body" },
  { name: "Cable row / pulley basso", muscleGroup: "Dorso", slug: "cable-row", loadType: "weight" },
  { name: "Croci manubri", muscleGroup: "Petto", slug: "dumbbell-chest-fly", loadType: "weight" },
  { name: "Triceps pushdown", muscleGroup: "Tricipiti", slug: "triceps-pushdown", loadType: "weight" },
  { name: "Hammer curl", muscleGroup: "Bicipiti", slug: "hammer-curl", loadType: "weight" },
  { name: "Leg extension", muscleGroup: "Gambe", slug: "leg-extension", loadType: "weight" },
  { name: "Bulgarian split squat", muscleGroup: "Gambe", slug: "bulgarian-split-squat", loadType: "body" },
  { name: "Step-up box", muscleGroup: "Gambe", slug: "step-up-box", loadType: "body" },
  { name: "Kettlebell swing", muscleGroup: "Full body", slug: "kettlebell-swing", loadType: "weight" },
  { name: "Bicycle crunch", muscleGroup: "Core", slug: "bicycle-crunch", loadType: "body" },
  { name: "Curl con bilanciere", muscleGroup: "Bicipiti", slug: "barbell-curl", loadType: "weight" },
  { name: "Trazioni", muscleGroup: "Dorso", slug: "trazioni", loadType: "body" },
  { name: "French press", muscleGroup: "Tricipiti", slug: "french-press", loadType: "weight" },
  { name: "Lat machine", muscleGroup: "Dorso", slug: "lat-machine", loadType: "weight" },
  { name: "Rematore con bilanciere", muscleGroup: "Dorso", slug: "barbell-row", loadType: "weight" },
  { name: "Pressa", muscleGroup: "Gambe", slug: "pressa", loadType: "weight" },
  { name: "Croci ai cavi", muscleGroup: "Petto", slug: "cable-chest-fly", loadType: "weight" },
  { name: "Spinte con manubri", muscleGroup: "Petto", slug: "dumbbell-press", loadType: "weight" },
  { name: "Lento avanti", muscleGroup: "Spalle", slug: "lento-avanti", loadType: "weight" },
  { name: "Panca piana", muscleGroup: "Petto", slug: "flat-bench-press", loadType: "weight" },
  { name: "High knees", muscleGroup: "Cardio", slug: "high-knees", loadType: "time" },
  { name: "Battle ropes", muscleGroup: "Cardio", slug: "battle-ropes", loadType: "time" },
  { name: "Calf raise seduto", muscleGroup: "Polpacci", slug: "seated-calf-raise", loadType: "weight" },
  { name: "Slanci glutei al cavo", muscleGroup: "Glutei", slug: "cable-glute-kickback", loadType: "weight" },
  { name: "Abductor machine", muscleGroup: "Glutei", slug: "hip-abductor-machine", loadType: "weight" },
  { name: "Farmer walk", muscleGroup: "Full body", slug: "farmer-walk", loadType: "time" },
  { name: "Preacher curl", muscleGroup: "Bicipiti", slug: "preacher-curl", loadType: "weight" },
  { name: "Estensioni tricipiti sopra testa", muscleGroup: "Tricipiti", slug: "overhead-triceps-extension", loadType: "weight" },
  { name: "Face pull", muscleGroup: "Spalle", slug: "face-pull", loadType: "weight" },
  { name: "Reverse fly", muscleGroup: "Spalle", slug: "reverse-fly", loadType: "weight" },
  { name: "Calf raise in piedi", muscleGroup: "Polpacci", slug: "standing-calf-raise", loadType: "weight" },
  { name: "Donkey calf raise", muscleGroup: "Polpacci", slug: "donkey-calf-raise", loadType: "weight" },
  { name: "Curl concentrato", muscleGroup: "Bicipiti", slug: "concentration-curl", loadType: "weight" },
  { name: "Curl manubri inclinato", muscleGroup: "Bicipiti", slug: "incline-dumbbell-curl", loadType: "weight" },
  { name: "Dip su panca", muscleGroup: "Tricipiti", slug: "bench-dips", loadType: "body" },
  { name: "Clean and press", muscleGroup: "Full body", slug: "clean-and-press", loadType: "weight" },
  { name: "Medicine ball slam", muscleGroup: "Full body", slug: "medicine-ball-slam", loadType: "weight" },
  { name: "Box jump", muscleGroup: "Cardio", slug: "box-jump", loadType: "body" },
  { name: "Salto con la corda", muscleGroup: "Cardio", slug: "jump-rope", loadType: "time" },
  { name: "Cable pull-through", muscleGroup: "Glutei", slug: "cable-pull-through", loadType: "weight" },
  { name: "Calf raise monopodalico", muscleGroup: "Polpacci", slug: "single-leg-calf-raise", loadType: "body" },
  { name: "Tibialis raise", muscleGroup: "Polpacci", slug: "tibialis-raise", loadType: "body" },
  { name: "Sled push", muscleGroup: "Full body", slug: "sled-push", loadType: "weight" },
  { name: "Rowing machine", muscleGroup: "Cardio", slug: "rowing-machine", loadType: "time" },
  { name: "Cable woodchopper", muscleGroup: "Core", slug: "cable-woodchopper", loadType: "weight" },
  { name: "Alzata laterale al cavo", muscleGroup: "Spalle", slug: "cable-lateral-raise", loadType: "weight" },
  { name: "Diamond push-up", muscleGroup: "Petto", slug: "diamond-push-up", loadType: "body" },
  { name: "Estensione tricipiti con corda", muscleGroup: "Tricipiti", slug: "rope-overhead-triceps-extension", loadType: "weight" },
  { name: "Back extension", muscleGroup: "Dorso", slug: "back-extension", loadType: "body" },
  { name: "Hanging leg raise", muscleGroup: "Core", slug: "hanging-leg-raise", loadType: "body" },
  { name: "Curl bicipiti al cavo", muscleGroup: "Bicipiti", slug: "cable-biceps-curl", loadType: "weight" },
  { name: "Reverse curl", muscleGroup: "Bicipiti", slug: "reverse-curl", loadType: "weight" },
  { name: "Panca presa stretta", muscleGroup: "Tricipiti", slug: "close-grip-bench-press", loadType: "weight" },
  { name: "Skull crusher su panca", muscleGroup: "Tricipiti", slug: "skull-crusher-bench", loadType: "weight" },
  { name: "Shoulder press machine", muscleGroup: "Spalle", slug: "seated-shoulder-press-machine", loadType: "weight" },
  { name: "Arnold press", muscleGroup: "Spalle", slug: "arnold-press", loadType: "weight" },
  { name: "Dip petto", muscleGroup: "Petto", slug: "chest-dip", loadType: "body" },
  { name: "Pec deck", muscleGroup: "Petto", slug: "pec-deck-machine", loadType: "weight" },
  { name: "Crunch al cavo", muscleGroup: "Core", slug: "cable-crunch", loadType: "weight" },
  { name: "Glute kickback machine", muscleGroup: "Glutei", slug: "glute-kickback-machine", loadType: "weight" },
  { name: "Calf press alla pressa", muscleGroup: "Polpacci", slug: "calf-press-leg-press", loadType: "weight" },
  { name: "Tibialis raise seduto", muscleGroup: "Polpacci", slug: "seated-tibialis-raise", loadType: "body" },
  { name: "Abduzione anca al cavo", muscleGroup: "Glutei", slug: "cable-hip-abduction", loadType: "weight" },
  { name: "Frog pump", muscleGroup: "Glutei", slug: "frog-pump", loadType: "body" },
  { name: "Thruster con manubri", muscleGroup: "Full body", slug: "dumbbell-thruster", loadType: "weight" },
  { name: "Bear crawl", muscleGroup: "Full body", slug: "bear-crawl", loadType: "time" },
  { name: "Skater jump", muscleGroup: "Cardio", slug: "skater-jump", loadType: "body" },
  { name: "Squat jump", muscleGroup: "Cardio", slug: "squat-jump", loadType: "body" },
  { name: "Pulldown braccia tese", muscleGroup: "Dorso", slug: "straight-arm-pulldown", loadType: "weight" },
  { name: "Spider curl", muscleGroup: "Bicipiti", slug: "spider-curl", loadType: "weight" },
  { name: "Cyclette", muscleGroup: "Cardio", slug: "cyclette", loadType: "time" },
  { name: "TOP cardio", muscleGroup: "Cardio", slug: "top-cardio", loadType: "time" },
  { name: "Stacchi gambe tese", muscleGroup: "Gambe", slug: "stiff-leg-deadlift", loadType: "weight" },
  { name: "Low-row a carico libero", muscleGroup: "Dorso", slug: "low-row-plate-loaded", loadType: "weight" },
  { name: "Trazioni presa inversa", muscleGroup: "Dorso", slug: "reverse-grip-pull-up", loadType: "body" },
  { name: "Curl hammer al cavo basso", muscleGroup: "Bicipiti", slug: "cable-hammer-curl", loadType: "weight" },
  { name: "Panca inclinata manubri", muscleGroup: "Petto", slug: "incline-dumbbell-press", loadType: "weight" },
  { name: "Chiusure a libro", muscleGroup: "Core", slug: "knee-tuck-crunch", loadType: "body" },
  { name: "Curl bicipiti ST", muscleGroup: "Bicipiti", slug: "suspension-trainer-biceps-curl", loadType: "weight" },
  { name: "Skip", muscleGroup: "Cardio", slug: "high-knees", loadType: "time" },
  { name: "Squat con bilanciere", muscleGroup: "Gambe", slug: "barbell-squat", loadType: "weight" },
  { name: "Elastico per spalle", muscleGroup: "Riscaldamento", slug: "shoulder-band-warmup", loadType: "body" },
  { name: "Aperture toraciche", muscleGroup: "Riscaldamento", slug: "thoracic-open-book", loadType: "time" },
  { name: "Chest press", muscleGroup: "Petto", slug: "chest-press", loadType: "weight" },
  { name: "Pullover ai cavi", muscleGroup: "Dorso", slug: "cable-pullover", loadType: "weight" },
  { name: "Dead bug", muscleGroup: "Core", slug: "dead-bug", loadType: "time" },
  { name: "Bird dog", muscleGroup: "Core", slug: "bird-dog", loadType: "time" },
  { name: "Band pull apart", muscleGroup: "Postura", slug: "band-pull-apart", loadType: "body" },
  { name: "Wall slide", muscleGroup: "Postura", slug: "wall-slide", loadType: "time" },
  { name: "Broad jump", muscleGroup: "Cardio", slug: "broad-jump", loadType: "body" },
  { name: "Salti monopodici", muscleGroup: "Cardio", slug: "single-leg-hops", loadType: "body" },
  { name: "Trap bar deadlift", muscleGroup: "Gambe", slug: "trap-bar-deadlift", loadType: "weight" },
  { name: "Pallof press", muscleGroup: "Core", slug: "pallof-press", loadType: "weight" },
  { name: "Romanian Deadlift", muscleGroup: "Gambe", slug: "stiff-leg-deadlift", loadType: "weight" },
];

export const EXERCISE_SLUG_BY_NAME = new Map(EXERCISE_CATALOG.map((exercise) => [exercise.name, exercise.slug]));
