export const EXERCISE_CATALOG = [
  { name: "Piegamenti", muscleGroup: "Petto", slug: "push-up" },
  { name: "Squat", muscleGroup: "Gambe", slug: "squat" },
  { name: "Plank", muscleGroup: "Core", slug: "plank" },
  { name: "Crunch", muscleGroup: "Core", slug: "crunch" },
  { name: "Affondi", muscleGroup: "Gambe", slug: "lunge" },
  { name: "Shoulder press", muscleGroup: "Spalle", slug: "shoulder-press" },
  { name: "Curl bicipiti", muscleGroup: "Bicipiti", slug: "biceps-curl" },
  { name: "Mountain climber", muscleGroup: "Core", slug: "mountain-climber" },
  { name: "Burpee", muscleGroup: "Full body", slug: "burpee" },
  { name: "Jumping jack", muscleGroup: "Cardio", slug: "jumping-jack" },
  { name: "Panca manubri", muscleGroup: "Petto", slug: "dumbbell-bench-press" },
  { name: "Rematore manubrio", muscleGroup: "Dorso", slug: "dumbbell-row" },
  { name: "Glute bridge", muscleGroup: "Glutei", slug: "glute-bridge" },
  { name: "Dip tricipiti", muscleGroup: "Tricipiti", slug: "triceps-dip" },
  { name: "Side plank", muscleGroup: "Core", slug: "side-plank" },
  { name: "Stacco da terra", muscleGroup: "Gambe", slug: "deadlift" },
  { name: "Lat machine / trazioni assistite", muscleGroup: "Dorso", slug: "lat-machine-assisted-pull-up" },
  { name: "Leg press", muscleGroup: "Gambe", slug: "leg-press" },
  { name: "Leg curl", muscleGroup: "Gambe", slug: "leg-curl" },
  { name: "Calf raise", muscleGroup: "Polpacci", slug: "calf-raise" },
  { name: "Russian twist", muscleGroup: "Core", slug: "russian-twist" },
  { name: "Sit-up", muscleGroup: "Core", slug: "sit-up" },
  { name: "Hip thrust", muscleGroup: "Glutei", slug: "hip-thrust" },
  { name: "Alzate laterali", muscleGroup: "Spalle", slug: "lateral-raise" },
  { name: "Military press / push press", muscleGroup: "Spalle", slug: "military-press-push-press" },
  { name: "Pull-up / trazione sbarra", muscleGroup: "Dorso", slug: "pull-up" },
  { name: "Cable row / pulley basso", muscleGroup: "Dorso", slug: "cable-row" },
  { name: "Croci manubri", muscleGroup: "Petto", slug: "dumbbell-chest-fly" },
  { name: "Triceps pushdown", muscleGroup: "Tricipiti", slug: "triceps-pushdown" },
  { name: "Hammer curl", muscleGroup: "Bicipiti", slug: "hammer-curl" },
  { name: "Leg extension", muscleGroup: "Gambe", slug: "leg-extension" },
  { name: "Bulgarian split squat", muscleGroup: "Gambe", slug: "bulgarian-split-squat" },
  { name: "Step-up box", muscleGroup: "Gambe", slug: "step-up-box" },
  { name: "Kettlebell swing", muscleGroup: "Full body", slug: "kettlebell-swing" },
  { name: "Bicycle crunch", muscleGroup: "Core", slug: "bicycle-crunch" },
];

export const EXERCISE_SLUG_BY_NAME = new Map(EXERCISE_CATALOG.map((exercise) => [exercise.name, exercise.slug]));
